#!/usr/bin/env python3
"""Local operator inbox. Python standard library; no listening network port."""
import argparse
import contextlib
import json
import os
from pathlib import Path
import sqlite3
import sys
import threading
import time
import uuid

# The shell watches the plugin directory; generated bytecode must not reload it.
sys.dont_write_bytecode = True

ROOT = Path(__file__).resolve().parent
from agent_policy import policy
INSTRUCTIONS = policy()
PRESENCE_TTL = 15


def process_identity(pid):
    """Linux boot + process start time distinguishes a live server from PID reuse."""
    try:
        fields = Path(f"/proc/{int(pid)}/stat").read_text().rsplit(")", 1)[1].split()
        if fields[0] in ("Z", "X"):
            return None
        return Path("/proc/sys/kernel/random/boot_id").read_text().strip() + ":" + fields[19]
    except (OSError, ValueError, IndexError):
        return None


def clean(value, name, limit=12000, required=False):
    if not isinstance(value, str) or len(value) > limit:
        raise ValueError(f"Invalid {name}")
    value = value.strip()
    if required and not value:
        raise ValueError(f"{name} is required")
    return value


class Store:
    def __init__(self, directory=None):
        self.directory = Path(directory or os.environ.get("OPERATOR_TODOS_DATA", "") or
                              Path(os.environ.get("XDG_DATA_HOME", str(Path.home() / ".local/share"))) / "operator-todos")
        self.directory.mkdir(parents=True, exist_ok=True, mode=0o700)
        self.path = self.directory / "todos.sqlite3"
        with self.db() as db:
            db.execute("PRAGMA journal_mode=WAL")
            db.execute("CREATE TABLE IF NOT EXISTS items (id TEXT PRIMARY KEY, source TEXT, session TEXT, request_key TEXT, body TEXT, UNIQUE(source, session, request_key))")
            db.execute("CREATE TABLE IF NOT EXISTS revision (id INTEGER PRIMARY KEY CHECK(id=1), value INTEGER)")
            db.execute("INSERT OR IGNORE INTO revision VALUES(1,0)")
            db.execute("CREATE TABLE IF NOT EXISTS connections (source TEXT, mode TEXT, client TEXT, seen REAL, PRIMARY KEY(source,mode))")
            db.execute("CREATE TABLE IF NOT EXISTS mcp_sessions (id TEXT PRIMARY KEY, source TEXT, client TEXT, pid INTEGER, identity TEXT, seen REAL)")
        self.path.chmod(0o600)

    @contextlib.contextmanager
    def db(self, write=False):
        db = sqlite3.connect(self.path, timeout=10)
        try:
            if write:
                db.execute("BEGIN IMMEDIATE")
            yield db
            db.commit()
        except BaseException:
            db.rollback()
            raise
        finally:
            db.close()

    def save(self, db, item):
        item["updated_at"] = time.time()
        db.execute("UPDATE items SET body=? WHERE id=?", (json.dumps(item, ensure_ascii=False), item["id"]))
        db.execute("UPDATE revision SET value=value+1 WHERE id=1")

    def record_connection(self, source, mode, client):
        with self.db(True) as db:
            db.execute("INSERT OR REPLACE INTO connections VALUES(?,?,?,?)", (source, mode, str(client)[:120], time.time()))

    def connections(self):
        with self.db() as db:
            return [dict(source=r[0], mode=r[1], client=r[2], seen=r[3]) for r in db.execute("SELECT source,mode,client,seen FROM connections")]

    def open_connection(self, connection_id, source, client):
        with self.db(True) as db:
            db.execute("DELETE FROM mcp_sessions WHERE seen<?", (time.time() - 86400,))
            db.execute("INSERT OR REPLACE INTO mcp_sessions VALUES(?,?,?,?,?,?)",
                       (connection_id, source, str(client)[:120], os.getpid(), process_identity(os.getpid()), time.time()))

    def heartbeat(self, connection_id):
        with self.db(True) as db:
            db.execute("UPDATE mcp_sessions SET seen=? WHERE id=?", (time.time(), connection_id))

    def close_connection(self, connection_id):
        with self.db(True) as db:
            db.execute("DELETE FROM mcp_sessions WHERE id=?", (connection_id,))

    def live_agents(self):
        with self.db() as db:
            rows = db.execute("SELECT source,pid,identity FROM mcp_sessions WHERE seen>?", (time.time() - PRESENCE_TTL,)).fetchall()
        counts = {}
        for source, pid, identity in rows:
            if identity and process_identity(pid) == identity:
                counts[source] = counts.get(source, 0) + 1
        return [dict(source=source, clients=counts[source]) for source in sorted(counts)]

    def fetch(self, db, item_id):
        row = db.execute("SELECT body FROM items WHERE id=?", (item_id,)).fetchone()
        if not row:
            raise ValueError("To-do not found")
        return json.loads(row[0])

    def post(self, data, source="manual"):
        source = clean(source, "source", 40, True)
        session = clean(data.get("session_id", ""), "session_id", 200)
        key = clean(data.get("request_key", ""), "request_key", 200, source != "manual") or str(uuid.uuid4())
        if source != "manual" and not (data.get("important") is True or data.get("explicitly_requested") is True):
            raise ValueError("Only important operator decisions or explicitly requested to-dos belong here")
        title = clean(data.get("title", ""), "title", 200, True)
        kind = data.get("kind", "task")
        if kind not in ("task", "approval", "choice", "reply"):
            raise ValueError("Invalid kind")
        term = data.get("term", "short")
        if term not in ("short", "long"):
            raise ValueError("Invalid term")
        context = clean(data.get("context", ""), "context", required=source != "manual")
        recommendation = clean(data.get("recommendation", ""), "recommendation", required=kind in ("approval", "choice"))
        consequence = clean(data.get("consequence", ""), "consequence", required=kind in ("approval", "choice"))
        options = data.get("options", [])
        if not isinstance(options, list) or len(options) > 8:
            raise ValueError("Use up to eight options")
        options = [clean(x, "option", 200, True) for x in options]
        if kind == "choice" and len(options) < 2:
            raise ValueError("A choice needs at least two options")
        if len(set(options)) != len(options):
            raise ValueError("Options must be unique")
        url = clean(data.get("chat_url", ""), "chat_url", 2000)
        if url and not url.startswith(("https://", "codex://threads/", "claude://", "hermes://")):
            raise ValueError("Use a conversation URL, not a command or file path")
        if not url and source == "codex" and session:
            try:
                uuid.UUID(session)
                url = "codex://threads/" + session
            except ValueError:
                pass
        with self.db(True) as db:
            row = db.execute("SELECT body FROM items WHERE source=? AND session=? AND request_key=?", (source, session, key)).fetchone()
            if row:
                # A repeated model call must not reopen a dismissed or answered decision,
                # nor silently change the action the operator is reviewing.
                return json.loads(row[0])
            item = dict(id=str(uuid.uuid4()), source=source, session_id=session,
                        request_key=key, title=title, kind=kind, term=term,
                        context=context, recommendation=recommendation,
                        consequence=consequence, options=options,
                        project=clean(data.get("project", ""), "project", 200),
                        chat_url=url, status="open", response=None,
                        delivery="", delivery_error="", created_at=time.time(),
                        updated_at=time.time(), snoozed_until=0, waiting_until=0,
                        important=data.get("important") is True)
            db.execute("INSERT INTO items VALUES(?,?,?,?,?)", (item["id"], source, session, key, json.dumps(item)))
            self.save(db, item)
            return item

    def snapshot(self):
        with self.db() as db:
            items = [json.loads(r[0]) for r in db.execute("SELECT body FROM items")]
            rev = db.execute("SELECT value FROM revision WHERE id=1").fetchone()[0]
        now = time.time()
        attention = sum((i["status"] == "open" and i.get("snoozed_until", 0) <= now and i["source"] != "manual") or i.get("delivery") == "failed" for i in items)
        items = [i for i in items if i["status"] != "deleted"]
        items.sort(key=lambda i: (i["status"] != "open", not i.get("important", False), i["created_at"]))
        return {"revision": rev, "attention": attention, "items": items, "now": now, "live_agents": self.live_agents()}

    def get(self, item_id):
        with self.db() as db:
            return self.fetch(db, item_id)

    def act(self, data):
        action, item_id = data.get("action"), data.get("id")
        with self.db(True) as db:
            item = self.fetch(db, item_id)
            if action == "delete":
                # Keep only a deduplication tombstone, erasing the content.
                item = {k: item[k] for k in ("id", "source", "session_id", "request_key", "created_at")}
                item.update(status="deleted", response={"id": str(uuid.uuid4()), "action": "deleted", "text": "Deleted by operator. This is not approval."}, waiting_until=0)
            elif action == "restore":
                if item["status"] not in ("done", "dismissed"):
                    raise ValueError("Only items in History can be moved back")
                item.update(status="open", response=None, delivery="", delivery_error="",
                            snoozed_until=0, waiting_until=0)
            elif action == "move":
                if data.get("term") not in ("short", "long"):
                    raise ValueError("Invalid term")
                item["term"] = data["term"]
            elif action == "snooze":
                if item["status"] != "open":
                    raise ValueError("Only open requests can be snoozed")
                item["snoozed_until"] = time.time() + 3600
            elif action in ("approve", "reject", "reply", "choose", "done", "dismiss"):
                if item["status"] != "open":
                    raise ValueError("This item has already been handled")
                if action in ("approve", "reject") and item["kind"] != "approval":
                    raise ValueError("This item is not an approval")
                if action == "done" and item["kind"] != "task":
                    raise ValueError("Choose a response to this decision")
                value = clean(data.get("text", ""), "response", 12000, action in ("reply", "choose"))
                if action == "choose" and value not in item["options"]:
                    raise ValueError("This option is not part of the request")
                if action == "dismiss":
                    value = "Dismissed by operator. No approval was granted. Do not repeat this request unless asked or circumstances materially change."
                elif not value:
                    value = {"approve": "Approved for the exact action described.", "reject": "Rejected. Do not perform the proposed action.", "done": "The operator has completed this task."}[action]
                item["response"] = {"id": str(uuid.uuid4()), "action": action, "text": value, "at": time.time()}
                item["status"] = "dismissed" if action == "dismiss" else ("done" if item["source"] == "manual" else "answered")
                item["delivery"] = "saved" if item["source"] != "manual" else ""
            else:
                raise ValueError("Unknown action")
            self.save(db, item)
        return item

    def mark_delivery(self, item_id, state, error="", response_id=None):
        with self.db(True) as db:
            item = self.fetch(db, item_id)
            if response_id is not None and (item.get("response") or {}).get("id") != response_id:
                return item
            if item["status"] != "deleted" and item.get("delivery") != "acknowledged":
                item.update(delivery=state, delivery_error=error)
                self.save(db, item)
        return item

    def ack(self, item_id, response_id):
        with self.db(True) as db:
            item = self.fetch(db, item_id)
            if not item.get("response") or item["response"]["id"] != response_id:
                raise ValueError("Acknowledgement does not match the operator response")
            if item["status"] not in ("deleted", "dismissed"):
                item["status"] = "done"
            item["delivery"] = "acknowledged"
            self.save(db, item)
        return item

    def wait(self, item_id, seconds=50):
        seconds = max(0, min(float(seconds), 55))
        with self.db(True) as db:
            item = self.fetch(db, item_id)
            item["waiting_until"] = time.time() + seconds + 3
            self.save(db, item)
        end = time.monotonic() + seconds
        while True:
            item = self.get(item_id)
            if item.get("response"):
                if item.get("delivery") != "acknowledged":
                    item = self.mark_delivery(item_id, "received", response_id=item["response"]["id"])
                if item.get("response"):
                    return item
            if time.monotonic() >= end:
                return item
            time.sleep(.2)

    def dispatch_one(self):
        """Claim one saved reply across all bar instances; never retry uncertain sends."""
        item = None
        with self.db(True) as db:
            for (body,) in db.execute("SELECT body FROM items WHERE source='codex'"):
                candidate = json.loads(body)
                if candidate.get("delivery") == "sending" and time.time() - candidate["updated_at"] > 30:
                    candidate.update(delivery="failed", delivery_error="Delivery was interrupted. Check the original chat before sending again.")
                    self.save(db, candidate)
                if (candidate.get("status") == "answered" and candidate.get("delivery") == "saved"
                        and candidate.get("session_id") and candidate.get("waiting_until", 0) < time.time()
                        and time.time() - candidate["response"]["at"] >= 2):
                    item = candidate
                    item["delivery"] = "sending"
                    self.save(db, item)
                    break
        if item is not None:
            try:
                from codex_desktop import deliver
                deliver(item)
                self.mark_delivery(item["id"], "sent", response_id=item["response"]["id"])
            except Exception as exc:
                self.mark_delivery(item["id"], "failed", str(exc), response_id=item["response"]["id"])


def tool(name, description, props, required=(), read=False):
    return {"name": name, "description": description, "inputSchema": {"type": "object", "properties": props, "required": list(required), "additionalProperties": False},
            "annotations": {"readOnlyHint": read, "destructiveHint": False, "openWorldHint": False, "idempotentHint": True}}


def string(description=""):
    return {"type": "string", "description": description}


TOOLS = [
    tool("operator_post", INSTRUCTIONS, {
        "request_key": string("Stable key for this exact decision; reuse on repeated calls"),
        "session_id": string("Actual originating conversation/session ID, when known"),
        "title": string("Short actionable request"),
        "kind": {"type": "string", "enum": ["task", "approval", "choice", "reply"]},
        "term": {"type": "string", "enum": ["short", "long"]},
        "important": {"type": "boolean"}, "explicitly_requested": {"type": "boolean"},
        "context": string("What needs the operator and why; concrete scope and facts"),
        "recommendation": string("Recommended action and rationale; required for approval/choice"),
        "consequence": string("What each choice changes, including costs, recipients, or affected systems; required for approval/choice"),
        "options": {"type": "array", "items": string(), "maxItems": 8},
        "project": string(), "chat_url": string("Actual conversation link; never invent an ID")
    }, ("request_key", "title", "context", "kind", "term")),
    tool("operator_get", "Read an operator request and its actual response. Open, dismissed, and deleted requests are not approvals.", {"id": string()}, ("id",), True),
    tool("operator_list", "Find your requests and replies. Filter by this conversation's session_id when known.", {"session_id": string()}, (), True),
    tool("operator_wait", "Wait up to 55 seconds for the operator's response to an existing request. If still open, continue independent work or wait again while blocked. Do not repost it.", {"id": string(), "seconds": {"type": "number", "minimum": 0, "maximum": 55}}, ("id",), True),
    tool("operator_ack", "After reading an actual response, acknowledge its response ID and continue within that response's scope. Dismissal is not approval.", {"id": string(), "response_id": string()}, ("id", "response_id"))
]


def serve_mcp(store, source):
    lock = threading.Lock()
    connection_id = str(uuid.uuid4())
    initialized = threading.Event()
    stopped = threading.Event()

    def keep_alive():
        while not stopped.wait(5):
            if initialized.is_set():
                try:
                    store.heartbeat(connection_id)
                except sqlite3.Error:
                    # Failure to renew makes presence expire rather than claim connectivity.
                    pass

    keeper = threading.Thread(target=keep_alive, daemon=True)
    keeper.start()
    def emit(payload):
        with lock:
            print(json.dumps(payload, ensure_ascii=False), flush=True)

    def handle(req):
        request_id = req.get("id")
        try:
            method, params = req.get("method"), req.get("params", {})
            if method == "initialize":
                store.record_connection(source, "mcp", (params.get("clientInfo") or {}).get("name", "MCP client"))
                result = {"protocolVersion": params.get("protocolVersion", "2024-11-05"), "capabilities": {"tools": {}}, "serverInfo": {"name": "operator-todos", "version": "0.2.1"}, "instructions": INSTRUCTIONS}
            elif method == "ping":
                result = {}
            elif method == "tools/list":
                result = {"tools": TOOLS}
            elif method == "tools/call":
                name, args = params.get("name"), params.get("arguments", {})
                if name == "operator_post":
                    value = store.post(args, source)
                elif name == "operator_list":
                    value = [x for x in store.snapshot()["items"] if x["source"] == source and (not args.get("session_id") or x.get("session_id") == args["session_id"])]
                elif name in ("operator_get", "operator_wait", "operator_ack"):
                    if store.get(args["id"])["source"] != source:
                        raise ValueError("This request belongs to another integration")
                    value = store.get(args["id"]) if name == "operator_get" else store.wait(args["id"], args.get("seconds", 50)) if name == "operator_wait" else store.ack(args["id"], args["response_id"])
                else:
                    raise ValueError("Unknown tool")
                result = {"content": [{"type": "text", "text": json.dumps(value, ensure_ascii=False)}], "isError": False}
            elif method and method.startswith("notifications/"):
                return
            else:
                emit({"jsonrpc": "2.0", "id": request_id, "error": {"code": -32601, "message": "Method not found"}})
                return
            if request_id is not None:
                emit({"jsonrpc": "2.0", "id": request_id, "result": result})
                if method == "initialize" and not stopped.is_set():
                    store.open_connection(connection_id, source, (params.get("clientInfo") or {}).get("name", "MCP client"))
                    initialized.set()
        except Exception as exc:
            if request_id is not None:
                emit({"jsonrpc": "2.0", "id": request_id, "result": {"content": [{"type": "text", "text": str(exc)}], "isError": True}})

    # Keep ping and other independent calls responsive during a bounded wait.
    workers = []
    try:
        for raw in sys.stdin:
            try:
                req = json.loads(raw)
                if not isinstance(req, dict):
                    raise ValueError("Invalid request")
            except ValueError:
                emit({"jsonrpc": "2.0", "id": None, "error": {"code": -32700, "message": "Invalid JSON request"}})
                continue
            workers = [w for w in workers if w.is_alive()]
            if len(workers) >= 16:
                emit({"jsonrpc": "2.0", "id": req.get("id"), "error": {"code": -32000, "message": "Too many outstanding calls"}})
                continue
            worker = threading.Thread(target=handle, args=(req,), daemon=True)
            workers.append(worker)
            worker.start()
    finally:
        stopped.set()
        keeper.join(timeout=1)
        for worker in workers:
            worker.join(timeout=.2)
        store.close_connection(connection_id)


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("command", choices=["mcp", "watch", "list", "post", "act", "get", "ack", "instructions", "setup-status", "connect"])
    parser.add_argument("payload", nargs="?", default="{}", help="JSON argument, or - to read JSON from stdin")
    parser.add_argument("--source", default=os.environ.get("OPERATOR_TODOS_SOURCE", "manual"))
    args = parser.parse_args()
    if args.command == "instructions":
        print(INSTRUCTIONS)
        return
    store = Store()
    if args.command == "mcp":
        serve_mcp(store, args.source)
        return
    if args.command == "watch":
        last = None
        def dispatch():
            while True:
                try:
                    store.dispatch_one()
                except Exception:
                    pass
                time.sleep(1)
        threading.Thread(target=dispatch, daemon=True).start()
        while True:
            snap = store.snapshot()
            signature = (snap["revision"], snap["attention"], json.dumps(snap["live_agents"]))
            if signature != last:
                print(json.dumps(snap, ensure_ascii=False), flush=True)
                last = signature
            time.sleep(1)
    data = json.load(sys.stdin) if args.payload == "-" else json.loads(args.payload)
    if args.command in ("setup-status", "connect"):
        import install
        if args.command == "connect":
            install.connect(data.get("source"))
        result = install.status(store)
        if args.command == "connect":
            result["message"] = install.SETUP_MESSAGE
    elif args.command == "post":
        data.setdefault("session_id", os.environ.get("CODEX_THREAD_ID", "") if args.source == "codex" else "")
        result = store.post(data, args.source)
    elif args.command == "act":
        result = store.act(data)
    elif args.command == "get":
        result = store.get(data["id"])
    elif args.command == "ack":
        result = store.ack(data["id"], data["response_id"])
    else:
        result = store.snapshot()
    print(json.dumps({"ok": True, "result": result}, ensure_ascii=False))


if __name__ == "__main__":
    try:
        main()
    except BrokenPipeError:
        pass
    except Exception as exc:
        print(json.dumps({"ok": False, "error": str(exc)}), flush=True)
        sys.exit(1)
